INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_OFDM_CYCLIC_PREFIX OFDM_Cyclic_Prefix)

FIND_PATH(
    OFDM_CYCLIC_PREFIX_INCLUDE_DIRS
    NAMES OFDM_Cyclic_Prefix/api.h
    HINTS $ENV{OFDM_CYCLIC_PREFIX_DIR}/include
        ${PC_OFDM_CYCLIC_PREFIX_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    OFDM_CYCLIC_PREFIX_LIBRARIES
    NAMES gnuradio-OFDM_Cyclic_Prefix
    HINTS $ENV{OFDM_CYCLIC_PREFIX_DIR}/lib
        ${PC_OFDM_CYCLIC_PREFIX_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OFDM_CYCLIC_PREFIX DEFAULT_MSG OFDM_CYCLIC_PREFIX_LIBRARIES OFDM_CYCLIC_PREFIX_INCLUDE_DIRS)
MARK_AS_ADVANCED(OFDM_CYCLIC_PREFIX_LIBRARIES OFDM_CYCLIC_PREFIX_INCLUDE_DIRS)

