INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_VITERBI_ENCODER Viterbi_Encoder)

FIND_PATH(
    VITERBI_ENCODER_INCLUDE_DIRS
    NAMES Viterbi_Encoder/api.h
    HINTS $ENV{VITERBI_ENCODER_DIR}/include
        ${PC_VITERBI_ENCODER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    VITERBI_ENCODER_LIBRARIES
    NAMES gnuradio-Viterbi_Encoder
    HINTS $ENV{VITERBI_ENCODER_DIR}/lib
        ${PC_VITERBI_ENCODER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VITERBI_ENCODER DEFAULT_MSG VITERBI_ENCODER_LIBRARIES VITERBI_ENCODER_INCLUDE_DIRS)
MARK_AS_ADVANCED(VITERBI_ENCODER_LIBRARIES VITERBI_ENCODER_INCLUDE_DIRS)

